export const FETCH_PRODUCTS = "FETCH_PRODUCTS";

export const ADD_TO_CART = "ADD_TO_CART";

export const REMOVE_FROM_CART = "REMOVE_FROM_CART";

export const SET_SEARCH_TERM = "SET_SEARCH_TERM";

export const SET_CATEGORIES = "SET_CATEGORIES";

export const SET_SELECTED_CATEGORIES = "SET_SELECTED_CATEGORIES";
